version: "3.9"
services:
  frontend:
    build: .
    container_name: frontend
    restart: always
    ports:
      - "8082:80"   # access frontend at http://localhost:8082
    networks:
      - gateway_network
    depends_on:
      - api_gateway

networks:
  gateway_network:
    external: true
