services:
  api_gateway:
    build: .
    container_name: api_gateway
    restart: always
    ports:
      - "9000:80"     # host:container
    networks:
      - gateway_network
    depends_on:
      - patientservice
      # - appointmentservice (when you add it)
